### PR TITLE
Fix/ips from server

### LINKED ISSUE #27: Server connection result
Client should know whether connection to server is a success or not before it is able to enter any commands. If connection to server is a success, the list of commands are shown as per usual. Otherwise, client should not be able to send commands.

### PR DESCRIPTION
**Pull request by Sam-Mucyo**
fixes #27

### CODE REVIEW

File: src/server/main.cpp [hunk 1]
```diff
@@ -107,12 +111,7 @@ class AudioServiceImpl final : public audio_service::audio_service::Service {
 
     // Register client in the connected clients list
     std::string client_ip = context->peer();
-    {
-      std::lock_guard<std::mutex> lock(clients_mutex_);
-      connected_clients_[next_client_id_] = client_ip;
-      next_client_id_++;
-      LOG_INFO("Client connected: {}", client_ip);
-    }
+    RegisterClient(client_ip);
```
Comment (hjkim015) [inline src/server/main.cpp:114]: Why are we registering client multiple times? Once on line 114 and another on line 78?

**Review by hjkim015 — APPROVED** [review]
